services:
  db:
    image: postgres:15.4-alpine
    restart: always
    env_file:
      - .dockerenv
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/backup:/backup
    ports:
      - "5432:5432"

